Repository Combodo/itop-data-collector-base, pull requests merged in 2023-02, with the labels that each got.

#22 N°5902 - Handle smoothly empty or header-only CSV source filesby CSV collector
  core/csvcollector.class.inc.php
  test/CsvCollectorTest.php
  test/single_csv/csv_errors/empty_file.csv
  test/single_csv/csv_errors/empty_file_with_header.csv
Labels: bug, internal

#26 N°5868 - PHP 8 and PHP 8.1 : Add compatibility Collector base
  core/utils.class.inc.php
Labels: internal

#21 N°5884 - Fix missing attributes in aSkippedAttribute
  core/collector.class.inc.php
  test/JsonCollectorTest.php
  test/single_json/common/ITopPersonJsonCollector.class.inc.php
  test/single_json/ignored_attributes/ITopPersonJsonSourceCollector.json
  test/single_json/ignored_attributes/dataTest.json
  test/single_json/ignored_attributes/expected_generated.csv
  test/single_json/ignored_attributes/params.distrib.xml
Labels: bug, internal

#25 N°5950 - cleanup code and fix some futurs bugs in php 8.2
  core/collector.class.inc.php
  core/parameters.class.inc.php
  core/sqlcollector.class.inc.php
  core/utils.class.inc.php
  toolkit/dump_tasks.php
Labels: internal

#24 N°5979 - Remove PHP warning and hide test data collectors in iTop setup
  core/mappingtable.class.inc.php
  test/collector/attribute_isnullified/module.test-collector.php
  test/getproject/module/module.myproject.php
  test/single_csv/common/module.test-csvcollector.php
  test/single_json/common/module.data-collector-json.php
Labels: enhancement

#23 N°5749 - Lack of feedback in case of synchro
  core/callitopservice.class.inc.php
  core/collector.class.inc.php
  core/jsoncollector.class.inc.php
  core/restclient.class.inc.php
  core/utils.class.inc.php
  test/CollectorSynchroTest.php
  test/FakeCollector.php
  test/UtilsTest.php
Labels: enhancement

#27 N°5995 - Fix PHP warning on lookup when table is empty
  core/lookuptable.class.inc.php
Labels: enhancement, internal

#29 N°6012 - Use authentication via tokens to reach iTop
  conf/params.distrib.xml
  core/callitopservice.class.inc.php
  core/collector.class.inc.php
  core/dopostrequestservice.class.inc.php
  core/restclient.class.inc.php
  core/utils.class.inc.php
  test/CallItopServiceTest.php
  test/RestTest.php
  test/UtilsTest.php
Labels: enhancement, internal

#28 N°5996 - During creation of csv file, in function lookup remove warning if initial field is empty
  core/lookuptable.class.inc.php
  core/utils.class.inc.php
  test/LookupTest.php
Labels: internal
